### ISSUE TITLE
collada_urdf    urdf to dae faile

### ISSUE THREAD

**Issue by liuxuyang2000** [ros/collada_urdf#37]
rosrun collada_urdf urdf_to_collada ur3.urdf ur3.dae

[ERROR] [1593432530.874595068]: Could not open file [ur3.urdf] for parsing.
[ERROR] [1593432530.874709228]: failed to open urdf file ur3.urdf

**Comment by clalancette** [comment]
You have to give it the full path to the urdf file that you'd like to parse.

If you are still having problems, you'll have to give us a lot more information, like what ROS distribution you are using, and exactly what you are trying to do (with reproducible steps).

I'm going to close this out for now, but please feel free to keep commenting or reopening if you think there is a real bug here.

**Comment by liuxuyang2000** [comment]
I'll follow the official instructions. 
example：rosrun collada_urdf urdf_to_collada pr2.urdf pr2.dae.but，I made a mistake.
My version is melodic. I don't quite understand what you're saying about the full path, can you give an example?
Thank you very much for your answer.

**Comment by clalancette** [comment]
Assuming that you have `ros-melodic-urdf-tutorial` installed, you could run, for instance:

```
rosrun collada_urdf urdf_to_collada /opt/ros/melodic/share/urdf_tutorial/urdf/05-visual.urdf out.dae
```
