### ISSUE TITLE
collada to urdf does not need to depend on TF

### ISSUE THREAD

**Issue by sloretz** [ros/collada_urdf#6]
From ros/robot_model#119

This part of the code:
https://github.com/ros/robot_model/blob/19ac39ac7324237485a27664183442a93319a269/collada_urdf/src/collada_to_urdf.cpp#L345

seems to be the only reason collada urdf depends on TF. Removing it or using urdf::Pose instead will remove the dependency.

**Comment by clalancette** [comment]
After reading the comments on ros/robot_model#119, it's still not completely clear to me why we need to remove the dependency on tf.  @scpeters , since you were involved in that discussion (a long time ago), do you have any insights?

**Comment by scpeters** [comment]
I think it's convenient to reduce unnecessary dependencies when possible.

We could also introduce a dependency on ignition math, since it has quaternion and Matrix3 types and has been in Ubuntu since [xenial](https://packages.ubuntu.com/xenial/libignition-math2).

**Comment by tfoote** [comment]
It is always good to clean up dependencies when possible. The tf matrices bring in quite possible more than half the dependencies of the package: https://gist.github.com/tfoote/7e77918136d410d9f34e046065897895

Looking at that it also looks like roscpp is only being used for the console logging which could be removed in favor of console_bridge/rosconsole_bridge.



![collada_urdf](https://user-images.githubusercontent.com/447804/28736787-634290f4-73a0-11e7-892d-48392bd816dc.png)

**Comment by sloretz** [comment]
I propose solving this before releasing into ROS Melodic, and maybe sooner. The `tf` package has been deprecated for a long time. Not depending on it here will mean one less package holding back its eventual retirement.

**Comment by clalancette** [comment]
Looking at this again, it seems like there are a few options for replacing the tf dependency:

1.  Switch to using tf2, since it has equivalent Quaternion and Matrix classes.  This will remove the tf dependency, but maybe not reduce the dependencies as far as we want.
1.  Switch to using ignition::math, which also has Quaternion and Matrix classes.  This removes the tf dependency, but adds a dependency on ignition::math.  This may or may not be a problem, though it certainly reduces the total number of dependencies.
1.  Switch to using Eigen, which also seems to have a Quaternion and Matrix class (based on a brief look).  This removes the tf dependency, and adds an Eigen dependency.  However, eigen is depended on in quite a few other places in ROS.

My preference here is to try to switch to Eigen first, and if I can't make that work, switch to tf2.  Other thoughts?

**Comment by tfoote** [comment]
I agree with using Eigen. The tf2 quaternion is designed for internal usage not as a general purpose linear math library. Clearly it can be used but if you just need those basic classes it is heavyweight.
